feat: offline token validation
adobe/aio-lib-ims-jwt pull request #32
Opened 2022-02-17 16:39 UTC by florind12

Added offline token validation method.

## Description

This PR requires changes in `aio-lib-ims`: https://github.com/adobe/aio-lib-ims/pull/92

## Related Issue
https://github.com/adobe/aio-cli-plugin-app/issues/386

## Motivation and Context

## How Has This Been Tested?
Unit tests.

Manual QA. 
Steps: 
1. Login via `aio auth`.
2. Modify `access_token`. 
3. `aio app init`

Expected: 
- Refresh token is used to generate new `access_token`.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-02-18 08:30 UTC, shazron requested changes

2022-02-18 08:30 UTC, shazron commented on src/helpers.js
> +      const URL = `https://static.adobelogin.com/keys/${env}/${certName}`
let's use https://github.com/adobe/aio-lib-core-networking with exponential backoff and use async/await.

2022-02-18 08:31 UTC, florind12 commented on src/helpers.js
> +  } catch (e) {
I totally forgot I can do that.

2022-02-18 08:35 UTC, shazron requested changes

2022-02-18 08:35 UTC, shazron commented on src/helpers.js
> +        aioLogger.debug('No cached certificate found, grab new one.')
"No cached certificate found, grabbing a new one." Can we also log the url, and where we are saving the cert

2022-03-07 02:34 UTC, shazron requested changes

2022-03-07 02:34 UTC, shazron commented on src/helpers.js
> + * Load local private key
this is a public key. We have to be careful with naming, and for security review. Private keys are never ever downloaded

2022-03-07 02:34 UTC, shazron commented on src/helpers.js
> +function loadPrivateKey (certName) {
loadPublicKey

2022-03-07 02:34 UTC, shazron commented on src/helpers.js
> + * @param certName name of the private key
public key

2022-03-07 02:34 UTC, shazron commented on src/helpers.js
> +      aioLogger.debug('Private key loaded from: %s', certLocation)
public key

2022-03-07 02:34 UTC, shazron commented on src/helpers.js
> +async function getPrivateKey (env, certName) {
getPublicKey

2022-03-07 02:34 UTC, shazron commented on src/helpers.js
> +    aioLogger.debug('Fetching a new private key...')
public key

2022-03-07 02:34 UTC, shazron commented on src/helpers.js
> +      aioLogger.debug('Private key saved at: %s', certLocation)
public key

2022-03-07 02:34 UTC, shazron commented on src/helpers.js
> +async function verifyJwt (token) {
The whole implementation is incorrect. This should not use jwt.verify (call it offlineTokenValidate or something to that effect), but verify the token according to the 6 clauses in the "Validating a token" section of the internal wiki page.

2023-04-24 16:23 UTC, closed without merging